#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Sep  2 11:13:35 2021

@author: matthewgoldenberg
"""

import requests
from bs4 import BeautifulSoup

URL = "https://realpython.github.io/fake-jobs/"
page = requests.get(URL)

print(page.text)


soup = BeautifulSoup(page.content "html.parser")
results_location = soup.find_all("p", class_="Location")
results_title = soup.find_all("h2", class_="title is-5")
print(results)


for result in results_location:
        print(result_location.text.strip())
for result results_title:
        print(results_title.text.strip())
